services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=RoofToolDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrong!Passw0rd
    ports:
      - "5432:5432"
    networks:
      - rooftool-network

  api:
    build:
      context: .
      dockerfile: RoofTool.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=RoofToolDb;Username=postgres;Password=YourStrong!Passw0rd;
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - rooftool-network

networks:
  rooftool-network:
    driver: bridge
