services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - rooftool-network

  api:
    build:
      context: .
      dockerfile: RoofTool.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=RoofToolDb;User ID=sa;Password=YourStrong!Passw0rd;
    depends_on:
      - db
    ports:
      - "5000:80"
    networks:
      - rooftool-network

networks:
  rooftool-network:
    driver: bridge